version: "3.5"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "testing"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "jaffle_shop"
    ports:
      - "5432:5432"


networks:
  default:
    name: dbt-test-net
